sudo: false
language: python
python:
- 2.7
- 3.5
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: R4I5qoH9Au8K4fyCRh1JYVILh6tYVWC1/PHWKmPlaMbGKOlmAkFuKu4bVBpb/5esOt6is/zIieumlcc61Og4ZruAAejq7aRb31mQLZSCwBBIbPvf+bIugwmQnWGuQA0u0++1AhHWbAmPgWT4pbLqZYXeOYbXhM96O9xy8dFzBKX1qnfrNdvHAAO9uMnl+a6yo77Y0vPpvKvgBgtfTKzck2/UpJDEQF78DMPFidZ6AYHwLEb4PfR2ZJw/wRe8NS/iCKjNv0kgFdPRG+kGR4iaS3jS8eS+2AKseErFYttDSjfKt4EWzTY9NqSFHqwPrn2n0mIo7MVY//HcSIFu+eeK2JM92H0Vh2ghi7QaGkj8+KvQzd5et6QlSPWRbJZ8tgvzgrz0xNJZC62yQW5x1N9/59/dNuLvx+qS/qJS2y5ZfZO1NkwVwqUQ59HCYmgdT/xb2Tfw5w1PwLRE5dEKTmt5jOs0XFP252vptEBMYYGxtO8R0VCc5EsLmOUI9k6Gt13O3Am4YNpXy/7kSxcdNQpk2vbhvLg9FBLs0w92AOfLMZasxpn5bnLLjYxAroXD8IhGDHrdW4lSeIEpPpUwGhdvx5kW5+01FsH4RarhAzPkiKFywrTijzpg0VlA6EXKUuwW7g1WOaBKG6pIC3P7N3ViuGvk0Abu8LUsw+Kc+tspP+s=
notifications:
  slack:
    secure: GA2vINLUW5ouVo9CKfyLYHMLWbeaaiJKGAwf1Q0Ue3N2ZZk0268EHz1nqHpM98pdO4uAYkP9Iph2+Z5WTXN9lLmNqvhAvDDEPL65V5AcJRSP362QSdeqNiLp9FhpHrdVHN9sg0btj0ZKsMn8M1Ei78uEsDTmkOODlhZNF93JC5WVcW0Zivr4HQfdttA5KMCcojPUwR0/YRpCT/onfAQ8MxRuqndrugza2CwPi8eIQszOkXKMyd/F9iJbotoUaLeu+SfViKrOG/lX9k/6NCm0APlYffDlDc6O2ZdLcX4cdtS30RobeLzVoJakE/I9kTZPgN8iJ1VlXcUaZnEn8Z+wh+/NtqLYdFyeG8ILjvxqVfNVMXNYWjNwIbYQ0IHrIbbK1ASvLZcgpJmR7Swzvf6CaZthaIE7+udsnIYim0qbatC8aCpilTMPH4L+umgwKgcXmLERiJGanhHxtB3KYxCtcYeL1toj6L32D4TVPzd0gETCOTyVdd91/QRU+MnRd6vKVrc2rwq1MRYhcpTw2ekPQ+MBqK62z4dBHu/6B1a3JOvVcS7DF4Lj5n2KsfukYTBap9wPjZRQUoYGStwhpTMXC3/FUqqTWCcHXLz8BEa9VIIdsgwTb5vUinJl/z6enTpYWN01h8FSE8ocU1L/3HNIt3IMsmA/JJ8LhWa6rcyCCok=
